# Performance optimizations for local development
spring.devtools.livereload.enabled=false

# Disable Kafka Auto-configuration for local development
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
